name: Build Container Image

on:
  push:

env:
  IMAGE_NAME: tam-utcomp
  IMAGE_TAGS: ${{ github.ref_name }} ${{ github.sha }}
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}/ut2
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    outputs:
      container-image: ${{ fromJSON(steps.push-to-registry.outputs.registry-paths)[0] }}

    steps:
      - uses: actions/checkout@v3

      - name: Buildah Build
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./Containerfile

      - name: Push to Registry
        id: push-to-registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-registry.outputs.registry-paths }}"

  sync-redirect:
    name: Synchronize Redirect
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate Manifest
        env:
          CONTAINER_IMAGE: ${{ needs.build.outputs.container-image }}
        run: podman run --rm -ti --entrypoint /bin/bash $CONTAINER_IMAGE echo 'test'
